djangoForm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from djuser import urls as djuserurl

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(djuserurl, namespace = 'djuser')),
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

djuser/urls.py
from django.urls import path
from djuser.views import views
from djuser.views.views import PasswordsChangeView

app_name = 'djuser'
urlpatterns = [
    path('signup', views.signUp, name='signup'),
    path('login', views.logIn, name='login'),
    path('logout', views.logOut, name='logout'),
    path('edit-profile', views.EditProfilePageView.as_view(), name='edit_profile'),
    path('<int:pk>/password/', PasswordsChangeView.as_view(), name='password'),
    path('', views.home_auth, name='home'),
]

djcore/models/models.py
from model_utils.models import TimeStampedModel
from model_utils import FieldTracker
from django.db import IntegrityError


class BaseStampStampModel(TimeStampedModel):
    tracker = FieldTracker()

    class Meta:
        abstract = True

    def delete(self, **kwargs):
        try:
            super().delete(**kwargs)

        except IntegrityError:
            raise "Integrity Error"

djform/models/models.py
from django.db import models

gender_choices = [
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Other', 'Other'),
]


class FormModel(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(blank=True, null=True)
    text_field = models.CharField(max_length=5000, blank=True, null=True)
    phone_number = models.CharField(max_length=14, blank=True, null=True)
    gender = models.CharField(choices=gender_choices, default='Male', max_length=15)
    address = models.CharField(max_length=255, blank=True, null=True)
    img_file = models.FileField(upload_to='img/', blank=True, null=True)
    video_file = models.FileField(upload_to='video/', blank=True, null=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

djui/models/models.py
from django.db import models

class CustomForm(models.Model):
    name = models.CharField(max_length=100)
    fields = models.JSONField(default=dict)  # Store form fields and types as a JSON object

    def __str__(self):
        return self.name

djuser/models.py
from django.db import models

# Create your models here.

djform/forms/forms.py
from django import forms
from djform.models.models import FormModel


class InputForms(forms.ModelForm):
    class Meta:
        model = FormModel
        fields = '__all__'

djuser/forms/forms.py
# from django import forms
# from djuser.models.models import UserProfile
#
# class UserProfileForm(forms.ModelForm):
#     class Meta:
#         model = UserProfile
#         fields = ['phone', 'address']

from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django import forms


class EditProfileForm(UserChangeForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    # username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = None

    class Meta:
        model = User
        # fields = ('username', 'first_name', 'last_name', 'email')
        fields = ('first_name', 'last_name', 'email')


class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}),
        label="Old Password"  # Change the label for the old_password field
    )
    new_password1 = forms.CharField(
        max_length=100,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}),
        label="New Password"  # Change the label for the new_password1 field
    )
    new_password2 = forms.CharField(
        max_length=100,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}),
        label="Confirm Password"  # Change the label for the new_password2 field
    )

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

djform/views/views.py
from django.shortcuts import render
from djform.forms.forms import InputForms


def form_view(request):
    form = InputForms()
    if request.method == 'POST':
        form = InputForms(request.POST)
        if form.is_valid():
            form.save()
    return render(request, 'djform/form.html', {'form': form})
# Create your views here.

djui/views/views.py
from django.shortcuts import render

# Create your views here.

djuser/views.py
from django.shortcuts import render

# Create your views here.

djuser/views/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView
from django.contrib.auth.models import User

from djuser.forms.forms import EditProfileForm, PasswordChangingForm


def signUp(request):
    if request.method == 'POST':
        firstName = request.POST['first_name']
        lastName = request.POST['last_name']
        userName = request.POST['username']
        email = request.POST['email']
        password = request.POST['password1']
        confirmPassword = request.POST['password2']
        user = User.objects.create_user(userName, email, password)
        user.first_name = firstName
        user.last_name = lastName
        if password != confirmPassword:
            return HttpResponse('Password does not match')
        user.save()
        return redirect('djuser:login')

    return render(request, 'djuser/signup.html')


def logIn(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('pass')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            next_url = request.GET.get('next', '')
            if next_url:
                return redirect(next_url)
            else:
                return redirect('djuser:home')
        else:
            return HttpResponse('Invalid Credentials')
    return render(request, 'djuser/login.html')


def logOut(request):
    logout(request)
    return redirect('djuser:login')


class EditProfilePageView(UpdateView):
    model = User
    form_class = EditProfileForm
    template_name = 'djuser/edit_profile.html'
    success_url = reverse_lazy('djuser:home')

    def get_object(self, **kwargs):
        return self.request.user


class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangingForm
    template_name = 'djuser/password.html'
    success_url = reverse_lazy('djuser:edit_profile')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Password changed successfully.')

        return response

def auth(request):
    if request.user.is_authenticated:
        return True
    else:
        return False


# @login_required(login_url='/login')
def home_auth(request):
    return render(request, 'home.html')

djform/templates/djform/form.html
<!DOCTYPE html>
<html>
<head>
    <title>User Profile</title>
</head>
<body>
    <h1>{{ profile.user.username }}'s Profile</h1>
    <p>Phone: {{ profile.phone }}</p>
    <p>Address: {{ profile.address }}</p>
</body>
</html>

djui/templates/djui/home.html
{% extends 'base.html' %}
{% block title %} Edit Profile {% endblock %}
{% block content %}
    <style>
        body {
            background-color: #080710;
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center;
            background-attachment: fixed;
            color: #ffffff;
        }

        .content-container {
            max-width: 30%;
            margin: 5% auto;
            padding: 20px;
        }
    </style>

<form method="POST" id="djui">
    {% csrf_token %}
    <div id="fields-container">
        <!-- Container for dynamically added fields -->
    </div>
    <button type="button" id="add-field-btn">Add Field</button>
    <input type="submit" value="Save Form">
</form>

<select id="field-type-select">
    <option value="CharField">Text</option>
    <option value="EmailField">Email</option>
    <option value="IntegerField">Number</option>
    <option value="FileField">File</option>
    <!-- Add more field types as needed -->
</select>

<script>
    document.getElementById('add-field-btn').addEventListener('click', function() {
        var selectedField = document.getElementById('field-type-select').value;
        // Add new input fields based on the selectedField type to #fields-container
    });
</script>
{% endblock %}

djuser/templates/djuser/auth.html
{% extends 'base.html' %}
{% block title %} Get Started! {% endblock %}
{% block content %}
    <style>
        body {
            background-color: #080710;
            filter: alpha(opacity=50);
        }
        .vl {
            border-left: 6px solid #ffffff;
            height: 200px;
            position: absolute;
            left: 50%;
            margin-left: -3px;
            top: 20%;
        }
        input[type=submit] {
            background-color: #238d0c;
            border: none;
            border-radius: 12px;
            color: white;
            padding: 16px 32px;
            text-decoration: none;
            {#margin-left: 45%;#}
            cursor: pointer;
            font-size: 20px;
            font-family: "Times New Roman", Times, serif;
        }


    </style>
    <h2 style = 'color: #ffffff; text-align: center'>You have to Log in First!</h2>
    <h3 style = 'color: #ffffff; position: absolute; left: 15%; top: 20%'>Already Have an Account?</h3>
    <form action="login">
        <input type="submit" value="Login" style="position: absolute; left: 23%; top: 30%">
    </form>


    <h3 style = 'color: #ffffff; position: absolute; left: 60%; top: 20%'>New User? You Have to Create an Account.</h3>
    <form action="signup">
        <input type="submit" value="SignUp" style="position: absolute; left: 73%; top: 30%">
    </form>
    <div class="vl"></div>
{% endblock %}

djuser/templates/djuser/edit_profile.html
{% extends 'base.html' %}
{% block title %} Edit Profile {% endblock %}
{% block content %}
    <style>
        body {
            background-color: #080710;
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center;
            background-attachment: fixed;
            color: #ffffff;
        }

        .content-container {
            max-width: 30%;
            margin: 5% auto;
            padding: 20px;
        }
    </style>


    <div class="container content-container">
        <h1 style="margin-top: 5%"> Update your Profile. </h1>

        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-info"><a href="{% url 'djuser:password' user.id %}" style="color: white">Reset Password</a></button>
            <button class="btn btn-secondary">Update Profile</button>
        </form>
    </div>
{% endblock %}

djuser/templates/djuser/login.html
{% extends 'base.html' %}
{% block title %} login {% endblock %}
{% block content %}

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}

form{
    height: auto;
    width: 40%;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
    {#margin-top: 7%;#}
}
form *{
    font-family: font-family: "Times New Roman", Times, serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 50px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
.social{
  margin-top: 30px;
  display: flex;
}
.social div{
  background: red;
  width: 150px;
  border-radius: 3px;
  padding: 5px 10px 10px 5px;
  background-color: rgba(255,255,255,0.27);
  color: #eaf0fb;
  text-align: center;
}
.social div:hover{
  background-color: rgba(255,255,255,0.47);
}
.social .fb{
  margin-left: 25px;
}
.social i{
  margin-right: 4px;
}

    </style>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form method="post">
        <h3>Login Here</h3>
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" placeholder="Enter Username" id="username" required name="username">

        <label for="password">Password</label>
        <input type="password" placeholder="Password" id="password" required name="pass">

        <button type="submit">Log In</button>

        <a href="{% url 'djuser:signup' %}">Create an account</a>
    </form>
{% endblock %}

djuser/templates/djuser/password.html
{% extends 'base.html' %}
{% block title %} Change Password {% endblock %}
{% block content %}
    <style>
        body {
                background-color: #080710;
                background-repeat: no-repeat;
                background-size: cover;
                background-position: center;
                background-attachment: fixed;
                color: #ffffff;
            }
        .content-container {
            max-width: 30%;
            margin: 5% auto;
            padding: 20px;
        }
    </style>


    <div class = 'container content-container'>
        <h1> Change Password. </h1>

        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-info">Confirm</button>
        </form>
    </div>
{% endblock %}

djuser/templates/djuser/signup.html
{% extends 'base.html' %}
{% block title %} signup {% endblock %}
{% block content %}

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}

form{
    height: auto;
    width: 40%;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
    margin-top: 7%;
}
form *{
    font-family: "Times New Roman", Times, serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 40px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 2px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 14px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
.social{
  margin-top: 30px;
  display: flex;
}
.social div{
    width: 150px;
    border-radius: 3px;
    padding: 5px 10px 10px 5px;
    background: rgba(255, 255, 255, 0.27);
    color: #eaf0fb;
    text-align: center;
}
.social div:hover{
  background-color: rgba(255,255,255,0.47);
}
.social .fb{
  margin-left: 25px;
}
.social i{
  margin-right: 4px;
}

    </style>

    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        <h3>Signup Here</h3>
        <label for="username">First Name</label>
        <input type="text" placeholder="First Name" required name="first_name" id="first_name">

        <label for="username">Last Name</label>
        <input type="text" placeholder="Last Name" required name="last_name" id="last_name">

        <label for="username">Username</label>
        <input type="text" placeholder="Username" required name="username" id="username">

        <label for="email">Email</label>
        <input type="email" placeholder="Email" required name="email" id="email">

        <label for="password1">Password</label>
        <input type="password" placeholder="Password" id="password1" required name="password1">


        <label for="password2">Confirm Password</label>
        <input type="password" placeholder="Confirm Password" id="password2" required name="password2">
        <button type="submit">Signup</button>

        <a href="{% url 'djuser:login' %}" >Already have an account?</a>
    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        .no-padding {
            padding-left: 0;
            padding-right: 0;
        }
    </style>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container-fluid no-padding">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'djuser:home' %}">Home</a>
                    </li>
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="{% url 'posts:browse' %}">Browse</a>#}
{#                    </li>#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="{% url 'predict:predict' %}">Predict Price</a>#}
{#                    </li>#}
                    <li class="nav-item">
                        <a class="nav-link" href="#">About Us</a>
                    </li>
                    </ul>
                    <div class="navbar-nav ml-auto"> <!-- This div aligns items to the right -->
                        <a class="nav-item nav-link" href="{% url 'djuser:edit_profile' %}">Profile</a>
                        <a class="nav-item nav-link" href="{% url 'djuser:logout' %}">Logout</a>
                    </div>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'djuser:home' %}">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="#">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'djuser:login' %}">Login</a>
                    </li>
                {% endif %}
        </div>
    </nav>
    <div>
        {% block content %}{% endblock %}
    </div>
</div>

<!-- Optional JavaScript; choose one of the two! -->
{#    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>#}
{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUuU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous">#}

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
        crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %} Welcome {% endblock %}
{% block content %}
    <style>
        body {
            background-color: #080710;
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center;
            background-attachment: fixed;
        }
        p {
            font-size: 25px;
            font-family: "Times New Roman", Times, serif;
            color: #ffffff;
            text-align: center;
            margin-top: 200px;
            margin-left: 200px;
            margin-right: 200px;
        }
        input[type=submit] {
            background-color: #238d0c;
            border: none;
            border-radius: 50px;
            color: white;
            padding: 16px 32px;
            text-decoration: none;
            margin-left: 45%;
            cursor: pointer;
            font-size: 20px;
            font-family: "Times New Roman", Times, serif;
        }
    </style>
    <div class="container my-5">
    <p>This platform is for those person who want to make a online form for collecting information, opinion, quiz, and so on.</p>

        <form action="#">
            <input type="submit" value="Get Started!">
        </form>
    </div>
{% endblock %}